layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: false
    projects:
    # - repo-name
      - suptimq.github.io

social_media:
  # behance: your_username
  # dribbble: your_username
  facebook: qiu.tin.5
  # hackerrank: your_username
  instagram: chiuuuul
  # keybase: your_username
  linkedin: tian-qiu-4b9a16190
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  twitter: Suptimq
  # unsplash: your_username
  # vk: your_username
  website: https://drive.google.com/open?id=1m6oXPOS6Ixa78_f93XWPaYNbRrNPp59a
  # youtube: your_username

topics:
  - name: Python
    web_url: https://www.python.org/
    image_url: assets/python-logo.png

  - name: Java
    web_url: https://www.java.com/en/
    image_url: assets/java-logo.png

  - name: Django
    web_url: https://www.djangoproject.com/
    image_url: assets/django-logo.png

  - name: Flask
    web_url: https://flask.palletsprojects.com/en/1.1.x/
    image_url: assets/flask-logo.png

  - name: Vue
    web_url: https://vuejs.org/
    image_url: assets/vue-logo.png

  - name: Angular
    web_url: https://angular.io/
    image_url: assets/angular-logo.png

  - name: NodeJS
    web_url: https://nodejs.org/en/
    image_url: assets/node-logo.png

  - name: MongoDB
    web_url: https://www.mongodb.com/
    image_url: assets/mongodb-logo.png