layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: false
    projects:
    # - repo-name
      - suptimq.github.io

social_media:
  # behance: your_username
  # dribbble: your_username
  facebook: qiu.tin.5
  # hackerrank: your_username
  instagram: chiuuuul
  # keybase: your_username
  linkedin: tian-qiu-4b9a16190
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  twitter: Suptimq
  # unsplash: your_username
  # vk: your_username
  website: https://drive.google.com/file/d/1btEW5xhASgtPhxrbsf4qqoB6_EZq5_c9/view?usp=sharing
  # youtube: your_username

topics:
  - name: Python
    image_url: assets/python-logo.png

  - name: Java
    image_url: assets/java-logo.png

  - name: Django
    image_url: assets/django-logo.png

  - name: Flask
    image_url: assets/flask-logo.png

  - name: Vue
    image_url: assets/vue-logo.png

  - name: Angular
    image_url: assets/angular-logo.png

  - name: NodeJS
    image_url: assets/node-logo.png

  - name: MongoDB
    image_url: assets/mongodb-logo.png
