layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: Chiu Tian
  # hackerrank: your_username
  instagram: chiuuuul
  # keybase: your_username
  linkedin: Tian Qiu
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  twitter: Tim
  # unsplash: your_username
  # vk: your_username
  website: https://drive.google.com/open?id=1m6oXPOS6Ixa78_f93XWPaYNbRrNPp59a
  # youtube: your_username

topics:
  - name: Python
    web_url: https://www.python.org/

  - name: Java
    web_url: https://www.java.com/en/

  - name: Django
    web_url: https://www.djangoproject.com/

  - name: Flask
    web_url: https://flask.palletsprojects.com/en/1.1.x/

  - name: MongoDB
    web_url: https://www.mongodb.com/

  - name: CSS
    web_url: https://github.com/topics/css
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/css/css.png

  - name: Web design